-- JAX-334: Add enrichment fields to companies
ALTER TABLE companies ADD COLUMN owner_name TEXT;
ALTER TABLE companies ADD COLUMN business_hours TEXT;
ALTER TABLE companies ADD COLUMN facebook_url TEXT;
ALTER TABLE companies ADD COLUMN instagram_url TEXT;
ALTER TABLE companies ADD COLUMN twitter_url TEXT;
ALTER TABLE companies ADD COLUMN linkedin_url TEXT;
ALTER TABLE companies ADD COLUMN yelp_url TEXT;
ALTER TABLE companies ADD COLUMN enriched_at TEXT;
ALTER TABLE companies ADD COLUMN enrichment_source TEXT;
