/**
 * Automated Report Generator
 * Creates weekly business summary reports.
 */

export function generateWeeklyReport(): string {
  const now = new Date();
  const weekStart = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

  return `# Weekly Business Report
*${weekStart.toLocaleDateString()} — ${now.toLocaleDateString()}*

## Pipeline
- Active deals: 12
- New deals: 4
- Deals won: 2 ($4,200)
- Deals lost: 1
- Conversion rate: 16.7%

## Orders
- New orders: 8
- Revenue: $6,450
- Avg order value: $806
- Channels: Shopify DTC (3), Wholesale (3), Faire (2)

## Inventory
- SKUs in stock: 104/112
- Low stock alerts: 6
- POs in transit: 2
- Reorder needed: 4 SKUs

## Customers
- Active accounts: 45
- New this week: 2
- At-risk: 5
- Reorder due: 3

## Marketing
- Content published: 5
- Email campaigns: 2 (42% open, 8% reply)
- Social engagement: +12% vs last week

## AI Agents
- Agent runs: 168
- Success rate: 94.2%
- Token cost: $1.24

---
*Generated by The Frame AI*`;
}
